import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { toast } from 'sonner';
import { Empty,Loading,PageHeader } from '../components/States';
import { api } from '../services/api';
import type { Candidate,Page,Stage } from '../types';
function useOwn(){return useQuery({queryKey:['own-candidate'],queryFn:async()=>{const p=await api<Page<Candidate>>('/candidates?page_size=1');return p.items[0]}})}
export function CandidateProfilePage(){const own=useOwn(),qc=useQueryClient();const [edit,setEdit]=useState(false);const save=useMutation({mutationFn:(body:Record<string,string>)=>api(`/candidates/${own.data?.id}`,{method:'PATCH',body:JSON.stringify(body)}),onSuccess:async()=>{setEdit(false);toast.success('Анкету оновлено');await qc.invalidateQueries({queryKey:['own-candidate']})}});if(own.isLoading)return <Loading/>;if(!own.data)return <Empty title="Анкету не знайдено" text="Зверніться до рекрутера."/>;const c=own.data,fields=['phone','email','city','address','education','skills','languages'] as const;return <><PageHeader title="Моя анкета" subtitle={`${c.public_id} · контактні та профільні дані`} actions={<button className="button primary" onClick={()=>setEdit(!edit)}>{edit?'Скасувати':'Редагувати'}</button>}/><form className="panel candidate-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=Object.fromEntries(fields.map(k=>[k,String(d.get(k)||'')])) as Record<string,string>;save.mutate(body)}}><div className="form-grid">{fields.map(k=><label key={k}>{k}<input name={k} defaultValue={c[k]??''} disabled={!edit}/></label>)}</div>{edit&&<button className="button primary" disabled={save.isPending}>Зберегти</button>}</form></>}
export function CandidateStatusPage(){const own=useOwn();const stages=useQuery({queryKey:['stages'],queryFn:()=>api<Stage[]>('/candidates/workflow/stages')});const history=useQuery({queryKey:['own-history',own.data?.id],queryFn:()=>api<{id:string;to_stage:string;created_at:string;comment?:string}[]>(`/candidates/${own.data?.id}/history`),enabled:Boolean(own.data)});if(own.isLoading||stages.isLoading)return <Loading/>;return <><PageHeader title="Мій статус" subtitle={`Поточний етап: ${own.data?.stage.name}`}/><div className="stage-track">{stages.data?.map(s=><div className={s.position<=(own.data?.stage.position??0)?'done':''} key={s.id}><i/><span>{s.name}</span></div>)}</div><section className="panel"><h2>Історія</h2>{history.data?.map(x=><article className="timeline" key={x.id}><b>{x.to_stage}</b><small>{new Date(x.created_at).toLocaleString('uk-UA')}</small><p>{x.comment}</p></article>)}</section></>}
type Note={id:string;title:string;message:string;read_at?:string;created_at:string};
export function NotificationsPage(){const qc=useQueryClient();const list=useQuery({queryKey:['notifications'],queryFn:()=>api<Note[]>('/notifications')});const read=useMutation({mutationFn:(id:string)=>api(`/notifications/${id}/read`,{method:'POST'}),onSuccess:()=>qc.invalidateQueries({queryKey:['notifications']})});if(list.isLoading)return <Loading/>;return <><PageHeader title="Повідомлення" subtitle="Події вашого відбору"/>{!list.data?.length?<Empty title="Повідомлень немає" text="Нові події з’являться тут."/>:<div className="notification-list">{list.data.map(n=><button className={`panel ${n.read_at?'':'unread'}`} key={n.id} onClick={()=>!n.read_at&&read.mutate(n.id)}><b>{n.title}</b><span>{n.message}</span><small>{new Date(n.created_at).toLocaleString('uk-UA')}</small></button>)}</div>}</>}
export function CandidateHomePage(){const own=useOwn();const notes=useQuery({queryKey:['notifications'],queryFn:()=>api<Note[]>('/notifications')});if(own.isLoading)return <Loading/>;const c=own.data;if(!c)return <Empty title="Анкета відсутня" text="Зверніться до рекрутера."/>;const values=[c.phone,c.email,c.city,c.education,c.speciality,c.skills,c.languages,c.desired_position],percent=Math.round(values.filter(Boolean).length/values.length*100);return <><PageHeader title={`Вітаємо, ${c.first_name}!`} subtitle="Актуальна інформація про ваш відбір"/><div className="candidate-hero"><div><small>ПОТОЧНИЙ ЕТАП</small><h2>{c.stage.name}</h2><p>Заповненість анкети: {percent}%</p></div><div className="progress-ring">{percent}<small>%</small></div></div><div className="grid-3"><section className="panel"><h3>Моя анкета</h3><p>{values.filter(Boolean).length} із {values.length} полів заповнено.</p></section><section className="panel"><h3>Шлях відбору</h3><p>{c.stage.name}</p></section><section className="panel"><h3>Сповіщення</h3><p>Непрочитаних: {notes.data?.filter(n=>!n.read_at).length??0}</p></section></div></>}
