import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Plus } from 'lucide-react';
import { useState,type FormEvent } from 'react';
import { toast } from 'sonner';
import { Empty,Loading,PageHeader } from '../components/States';
import { api } from '../services/api';
import type { Page } from '../types';
type UserRow={id:string;email:string;display_name:string;role:string;role_name:string;status:string;last_login_at?:string};type Audit={id:string;created_at:string;action:string;object_type?:string;description:string;ip_address?:string;request_id?:string};
export function UsersPage(){const qc=useQueryClient();const [show,setShow]=useState(false);const list=useQuery({queryKey:['users'],queryFn:()=>api<Page<UserRow>>('/users')});const action=useMutation({mutationFn:({id,op}:{id:string;op:string})=>api<{temporary_password?:string}>(`/users/${id}/${op}`,{method:'POST'}),onSuccess:async(data)=>{if(data.temporary_password)toast.success(`Тимчасовий пароль: ${data.temporary_password}`,{duration:10000});await qc.invalidateQueries({queryKey:['users']})}});const create=useMutation({mutationFn:(body:Record<string,string>)=>api('/users',{method:'POST',body:JSON.stringify(body)}),onSuccess:async()=>{setShow(false);await qc.invalidateQueries({queryKey:['users']})}});function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;create.mutate(d)}if(list.isLoading)return <Loading/>;return <><PageHeader title="Користувачі" subtitle="Облікові записи, блокування та сесії" actions={<button className="button primary" onClick={()=>setShow(!show)}><Plus/>Створити</button>}/>{show&&<form className="panel interview-form" onSubmit={submit}><label>Ім’я<input name="display_name" required/></label><label>Email<input name="email" type="email" required/></label><label>Роль<select name="role_code"><option value="recruiter">Рекрутер</option><option value="manager">Керівник</option><option value="operator">Оператор</option><option value="candidate">Кандидат</option></select></label><label>Тимчасовий пароль<input name="temporary_password" type="password" minLength={10} required/></label><button className="button primary">Створити</button></form>}<div className="table-wrap"><table><thead><tr><th>Користувач</th><th>Роль</th><th>Статус</th><th>Останній вхід</th><th>Дії</th></tr></thead><tbody>{list.data?.items.map(u=><tr key={u.id}><td><b>{u.display_name}</b><small>{u.email}</small></td><td>{u.role_name}</td><td><span className="badge">{u.status}</span></td><td>{u.last_login_at?new Date(u.last_login_at).toLocaleString('uk-UA'):'Немає'}</td><td><div className="actions"><button className="button ghost" onClick={()=>action.mutate({id:u.id,op:u.status==='blocked'?'unblock':'block'})}>{u.status==='blocked'?'Розблокувати':'Блокувати'}</button><button className="button ghost" onClick={()=>action.mutate({id:u.id,op:'reset-password'})}>Скинути пароль</button></div></td></tr>)}</tbody></table></div></>}
export function AuditPage(){const list=useQuery({queryKey:['audit'],queryFn:()=>api<Page<Audit>>('/audit')});if(list.isLoading)return <Loading/>;if(!list.data?.items.length)return <Empty title="Журнал порожній" text="Події з’являться після операцій."/>;return <><PageHeader title="Журнал дій" subtitle="Append-only аудит backend"/><div className="table-wrap"><table><thead><tr><th>Час</th><th>Дія</th><th>Опис</th><th>IP</th><th>Request ID</th></tr></thead><tbody>{list.data.items.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('uk-UA')}</td><td>{x.action}</td><td>{x.description}</td><td>{x.ip_address}</td><td><small>{x.request_id}</small></td></tr>)}</tbody></table></div></>}
