import { DndContext,useDraggable,useDroppable,type DragEndEvent } from '@dnd-kit/core';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState,type CSSProperties } from 'react';
import { toast } from 'sonner';
import { Empty,Loading,PageHeader } from '../components/States';
import { api } from '../services/api';
import type { Candidate,Page,Stage } from '../types';
export function WorkflowPage(){const qc=useQueryClient();const [q,setQ]=useState('');const stages=useQuery({queryKey:['stages'],queryFn:()=>api<Stage[]>('/candidates/workflow/stages')});const candidates=useQuery({queryKey:['kanban'],queryFn:()=>api<Page<Candidate>>('/candidates?page_size=100')});const move=useMutation({mutationFn:(x:{id:string;stageId:number;comment?:string;rejection_reason?:string})=>api(`/candidates/${x.id}/stage`,{method:'POST',body:JSON.stringify({stage_id:x.stageId,comment:x.comment,rejection_reason:x.rejection_reason})}),onError:async e=>{toast.error(e instanceof Error?e.message:'Перехід відхилено');await qc.invalidateQueries({queryKey:['kanban']})},onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:['kanban']}),qc.invalidateQueries({queryKey:['dashboard']})])}});if(stages.isLoading||candidates.isLoading)return <Loading/>;const filtered=candidates.data?.items.filter(c=>`${c.last_name} ${c.first_name} ${c.public_id}`.toLowerCase().includes(q.toLowerCase()))??[];function ended(e:DragEndEvent){const c=filtered.find(x=>x.id===e.active.id),target=stages.data?.find(x=>String(x.id)===e.over?.id);if(!c||!target||c.stage.id===target.id)return;const rejection_reason=target.code==='rejected'?prompt('Вкажіть причину відмови')?.trim():undefined;if(target.code==='rejected'&&!rejection_reason)return;const comment=target.code!=='rejected'?prompt('Коментар до переходу (необов’язково)')?.trim():undefined;qc.setQueryData<Page<Candidate>>(['kanban'],old=>old?{...old,items:old.items.map(x=>x.id===c.id?{...x,stage:target}:x)}:old);move.mutate({id:c.id,stageId:target.id,comment,rejection_reason})}return <><PageHeader title="Статуси та етапи" subtitle="Перетягніть кандидата до дозволеного етапу"/><input className="workflow-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Пошук кандидата"/><DndContext onDragEnd={ended}><div className="kanban">{stages.data?.map(s=><Column key={s.id} stage={s} items={filtered.filter(c=>c.stage.id===s.id)}/>)}</div></DndContext>{!filtered.length&&<Empty title="Кандидатів не знайдено" text="Змініть запит."/>}</>}
function Column({stage,items}:{stage:Stage;items:Candidate[]}){const {setNodeRef,isOver}=useDroppable({id:String(stage.id)});return <section ref={setNodeRef} className={isOver?'drop-active':''}><header><b>{stage.name}</b><span>{items.length}</span></header>{items.map(c=><Card key={c.id} candidate={c}/>)}{!items.length&&<div className="kanban-empty">Порожньо</div>}</section>}
function Card({candidate}:{candidate:Candidate}){const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:candidate.id});const style:CSSProperties={transform:transform?`translate3d(${transform.x}px,${transform.y}px,0)`:undefined,opacity:isDragging?.55:1};return <article ref={setNodeRef} style={style} {...listeners} {...attributes}><small>{candidate.public_id}</small><b>{candidate.last_name} {candidate.first_name}</b><span>{candidate.speciality||'Напрям не вказано'}</span></article>}
